### ISSUE TITLE
[Project][Feedback] Tindev

### ISSUE THREAD

**Issue by swapnadeepmohapatra** [tanaypratap/teamtanay.jobchallenge.dev#510] opened 2020-05-05 08:44 UTC
Hey Guys,

I hope you all are doing fine. I have made this full-stack Social Network App with MERN stack named **Tindev**. Researching co-workers is something difficult. Tindev offers you the opportunity to simply accelerate the process by finding out which is the best match. With this, you can log in with your GitHub ID and you can swipe through different devs and if two devs like each other then they match and they can chat over this app. Through this, they can get the best co-worker for them and maybe the co-founder of a big firm.

I also have converted this into a PWA so that it can be downloaded and can be used as a mobile app also a Windows app.

### Link of the site -> https://tindev.swapnadeep.com/

And thank you in advance for helping us out.

**Comment by suryanshsugandhi** [comment] 2020-05-05 20:46
I am not a mentor, but that looks clean and promising. If you're willing to work more on it, github sign in is very easy to implement. Swiped right on a lot of devs. Looking to connect xD

**Comment by swapnadeepmohapatra** [comment] 2020-05-06 03:34
I was working on the passport.js to do so but will see if GitHub login will be good to integrate with this.

**Comment by swapagarwal** [comment] 2020-05-07 15:50
@swapnadeepmohapatra Nice work! :)

Here's the detailed feedback:
* I liked the overall look of the app. The logo is good and relevant. Same goes for the app name.
* I entered my GitHub username and pressed enter. I liked that it worked and I didn't have to click the sign up button instead. I saw a loader for a few seconds and then an "OOPS" screen. I checked again and it's reproducible. It'd be great if you could **show a loading screen** there instead.
* Then I saw a card of a GitHub user with a name, avatar, and an optional description. I'm sort of lost here, because I'm looking for a "coding partner" and these details don't help much. I'd love to see some **relevant details** here, like the languages used by the user, maybe some of their popular repositories, etc. Think of how you'd find a buddy in real life.
* On the UI side, when I click on like/skip, the name changes quickly before the new image is loaded. So there's an inconsistent state in between where the name doesn't match the avatar. You can either **pre-load the image** or wait for the image to load before changing the name. It'd be perfect if you show an intermittent / loading screen in case you choose the latter implementation.
* Below the like/skip buttons, you have shown keyboard keys with labels. I'm assuming these are **keyboard shortcuts** but they don't work somehow.
* I got a match with you after some time. I didn't click on send message at that point and it wasn't shown in the **left menubar** under all matches. I saw it after refreshing the page. Minor nitpick.
* The messaging feature is functional and persistent. I couldn't test live chat though.
* Food for Thought / out of scope question: I'd love to know your thoughts on how would you attempt to sort the list of users to swipe on. Feel free to skip this question.

P.S. I liked your proactiveness. You wanted a review so you DMed folks. Simple as that. This is an underrated skill and it'll help you a lot in getting things done. Don't go overboard though (nobody likes spam :P)!

**Comment by swapnadeepmohapatra** [comment] 2020-05-07 19:19
Hello @swapagarwal .

Thank you for such a detailed review. I have taken care of many points.

-  I have now added a **loading screen** while the app is fetching the users from the backend. 
- Also, the **keyboard shortcuts** are added now. 
- And after a match, the **list is being updated.**
- I was about to ask the user to put manually some data like which tech stack he is using and some similar stuff, but I was suggested to not do so as we should ask the user as minimum information as possible. But I will add that fields too. As that requires a total schema redesign so it will take a bit of time (though it's built with NoSQL ).

#### Some other improvements 
- Also while clicking on the **brand logo** in the top navbar it redirects to the home page and the user had to log in again. Now it is solved, when the user is logged in, it redirects to the page where it shows all the users list. 
- Also, I have changed the position of the **message input box.**

#### More Scope of Improvements 
- I will add a push notification so that the user will get to know in case of any new matches or any new messages. 
- On clicking on the user's profile we can see his/her **profile** and choose whether to swipe left or right.  
- A **search bar** can be added in the left menubar to search through all the matches. 
- Also in the **desktop view**, I am thinking of bringing the left menubar on to the screen so that the desktop view doesn't look empty but on the smaller screens it will popup after clicking on the hamburger icon.

#### Food for Thought / out of scope question
- It would be a great idea to sort the users on the basis of the **followers** in their GitHub account. And further, this can be done on the basis of their **tech stack**. I think that would be a great parameter to measure the probability of swipe on. 

And thank you for helping me a lot in improving my site.

**Comment by swapnadeepmohapatra** [comment] 2020-05-09 17:36
Hello @swapagarwal ,

I have updated the website one more time. Here I have made the following changes. 

- I have changed the **color theme**. 
- I have added another page that will the **info of the user**. It shows the stats on the basis of the recent 30 public repos. It includes the percentage of each language used in the repos. 

![image](https://user-images.githubusercontent.com/41564532/81480576-3738ee80-9248-11ea-9e27-5ec614f0f20e.png)

Thanks,
Swapnadeep

**Comment by swapagarwal** [comment] 2020-05-10 08:14
@swapnadeepmohapatra Awesome! 🔥
Can you also attach the GitHub repo? I'll take a final look together. ✌️

**Comment by swapnadeepmohapatra** [comment] 2020-05-10 09:03
Thank you @swapagarwal 

Here is the GitHub Repo - 

[Forntend](https://github.com/swapnadeepmohapatra/tindev-frontend)
[Backend](https://github.com/swapnadeepmohapatra/tindev-backend)

**Comment by swapagarwal** [comment] 2020-05-19 10:01
Hey @swapnadeepmohapatra, I took a look at the updated site and you've incorporated most of the changes pretty fast so kudos for that. 💯

There's some scope of improvement in your coding style, e.g. use more descriptive names than `a,b,arr,pc`, avoid hardcoding css styles, etc. The good thing is that you'll learn these things with experience. You can get a head-start by reading the book `Clean Code`. Feel free to ping me on Telegram if you need any help.

Oh, and by the way, I can't believe you're in class 10th. You're doing amazing things! 🙌

**Comment by swapnadeepmohapatra** [comment] 2020-05-19 15:54
Thank you @swapagarwal . I am really bad at naming variables. I am trying to get better at this by taking a look at some of the enterprise-level open-source code.

**Closed** 2020-05-27 16:39 UTC
Labels: Project-Feedback, Reviewed-By-Mentor
